### ISSUE TITLE
Benchmark KPI's

### ISSUE THREAD

**Issue by GijsbertKruithof** [EURODEO/e-soh-kpis#1]
Have every institute review the list of KPIs, when it is ready. Do the institutes have any KPIs that must be included?

Depends on one review issue (in github) for each institute..

**Comment by tervo** [comment]
EUMETSAT data services KPIs are and target values are available at: https://www.eumetsat.int/media/45745 (pp. 105-107)

I took a screenshots of the pages here for convenience: 
<img width="1083" alt="Screenshot 2023-04-13 at 15 44 46" src="https://user-images.githubusercontent.com/2298380/231778094-17853b06-beab-4a84-b55e-ca2a6acf4742.png">
<img width="1030" alt="Screenshot 2023-04-13 at 15 45 01" src="https://user-images.githubusercontent.com/2298380/231778169-2ce8425e-0128-4c4b-95b7-e52289fe77c3.png">
<img width="1055" alt="Screenshot 2023-04-13 at 15 45 11" src="https://user-images.githubusercontent.com/2298380/231778225-b5c410f0-8b81-4d96-b15c-db3aedd8c870.png">

**Comment by tervo** [comment]
Check Oscar Rolling Requirements (Stuart promised to add link)

**Comment by tervo** [comment]
Checked https://space.oscar.wmo.int/requirements didn't see anything on availability but data timeliness is well defined for most parameters

**Comment by tervo** [comment]
[WIS2 technical specification](https://wmoomm.sharepoint.com/sites/wmocpdb/eve_activityarea/Forms/AllItems.aspx?id=%2Fsites%2Fwmocpdb%2Feve%5Factivityarea%2FWMO%20Information%20System%20%28WIS%29%5F6cf41395%2D0ffc%2Dea11%2Da813%2D000d3aafe55d%2Fdocs%20shared%20on%20community%20site%2FWIS%202%2E0%20Manual%20and%20Guidance%2FGuidance%20on%20technical%20specification%20of%20WIS2%2Dv2%2Epdf&parent=%2Fsites%2Fwmocpdb%2Feve%5Factivityarea%2FWMO%20Information%20System%20%28WIS%29%5F6cf41395%2D0ffc%2Dea11%2Da813%2D000d3aafe55d%2Fdocs%20shared%20on%20community%20site%2FWIS%202%2E0%20Manual%20and%20Guidance&p=true&ga=1) discuss availability requirements in "Part VI WIS Metrics" but do not specify them

**Comment by GijsbertKruithof** [comment]
ThX! I have included these sources in the introduction of the KPI document.
