### ISSUE TITLE
DWD benchmark KPI's

### ISSUE THREAD

**Issue by skremdwd** [EURODEO/e-soh-kpis#7]
Some feedback from DWD/OPERA team, may get some more information later:

OPERA related KPIs:

- Not that many defined KPIs
- Processing time from "inserted in db" to "send out to destination"
  - No transfer time measured, as these can vary quite a bit on different factors
- Uptime of 99.95%
  - With 24/7 operators
  - Christoph Müller (DWD/Opera) recommended for us =< 99% without 24/7 operators
- Monitoring is widely used
  - Disk space
  - RAM
  - CPU/Network/... Usage
  - Display with Grafana e.g.
  - Xymon, Icinga, CheckMk, ...

**Comment by GijsbertKruithof** [comment]
Thx! I'll close this issue now.
I think we can also use "Processing time from "inserted in db" to "send out to destination"
